djangobooks/urls.py
"""djangobooks URL Configuration
"""
from django.conf.urls import url
from django.contrib import admin
from books.views import CategoryListView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # homepage url.
    url(r'^$', CategoryListView.as_view(), name='category-list'), 

    
]

books/models.py
from django.db import models

# Create your models here.

from django.db import models


class BaseModelManager(models.Manager):
    """
    Base Manager
    """
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)
    



class BaseModel(models.Model):
    """
    Interface Base
    """    
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    
    objects = BaseModelManager()

    def set_deleted(self, *args, **kwargs):
        self.deleted = True
        self.save()
    
    class Meta:
        abstract = True    

        
class Category(BaseModel):
    """
    Category Object. i.e. thriller, fantasy..
    """
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=3)
    class Meta:
        verbose_name_plural = "categories"    
        
    def __str__(self):
        return self.name
        
        
class Author(BaseModel):
    """
    Author
    """
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    
    def __str__(self):
        return "%(first_name)s %(last_name)s" % dict(first_name=self.first_name, last_name=self.last_name)

class PublishingHouse(BaseModel):
    """
    Publishing House
    """
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name    
    
class Book(BaseModel):
    """
    The Book object.
    """
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    publishing_house = models.ForeignKey(PublishingHouse, on_delete=models.SET_NULL, null=True)  # a book can have +Authors
    authors = models.ManyToManyField(Author)

    title = models.CharField(max_length=100)
    description = models.TextField()
    published_at = models.DateField()

    def __str__(self):
        return self.title

books/views.py
from django.views.generic.list import ListView
from django.utils import timezone

from .models import Category

# I decided to group all books in Category; so I can create a Category's ListView

class CategoryListView(ListView):
    model = Category

templates/books/category_list.html
<html>
  <head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Hi!</h1>
            <h3>This is a django example</h3>
            <p>This is an example created using django. Note: to avoid calling collect static, the js and css are incluede via CDN ;)</p>
          </div>

            <h5>NOTE: The data are grouped by Category</h5>
            {% for category in object_list %}
              {% if category.book_set.all %}
                <div class="row">
                  <h2>{{ category }}</h2>
                  {% for book in category.book_set.all %}
                    {% include "books/include/book_item.html" %}
                  {% endfor %}
                </div><!--/row-->
              {% endif %}
            {% endfor %}
      <footer>
        <p>&copy; 2018 Marco Carminati.</p>
      </footer>

    </div><!--/.container-->
  </body>
</html>

templates/books/include/book_item.html
<div class="col-xs-6 col-lg-4">
  <h2>{{ book }}</h2>
  <dl>
    <dt>Description</dt>
    <dd>{{ book.description }}</dd>
  </dl>  
  <dl>
    <dt>Published at</dt>
    <dd>{{ book.published_at }}</dd>
  </dl>
  <dl>
    <dt>Publishing house</dt>
    <dd>{{ book.publishing_house }}</dd>
  </dl>    
  <dl>
    <dt>Author</dt>
    <dd>
      <ul>
        {% for author in book.authors.all %}
          <li>{{ author }}</li>
        {% endfor %}
      </ul>
    </dd>  
  </dl>
</div><!--/.col-xs-6.col-lg-4-->